version: '3'

services:
  overseer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - OVERSEER_HOST=0.0.0.0
      - OVERSEER_PORT=8000
      - OVERSEER_LOG_LEVEL=info
    volumes:
      - ${HOME}/.kube:/root/.kube
      - ${HOME}/.minikube:${HOME}/.minikube
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: python run.py 