apiVersion: v1
kind: ConfigMap
metadata:
  name: overseer-config
  namespace: a8s
data:
  OVERSEER_HOST: "0.0.0.0"
  OVERSEER_PORT: "8000"
  OVERSEER_LOG_LEVEL: "info"
---
apiVersion: v1
kind: Service
metadata:
  name: overseer-service
  namespace: a8s
spec:
  selector:
    app: overseer
  ports:
    - name: api
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: overseer-deployment
  namespace: a8s
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overseer
  template:
    metadata:
      labels:
        app: overseer
    spec:
      containers:
        - name: overseer
          image: a8s-overseer:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
              name: api
          envFrom:
            - configMapRef:
                name: overseer-config
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: overseer-ingress
  namespace: a8s
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /overseer(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: overseer-service
                port:
                  name: api 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: overseer-deployment-role
  namespace: a8s
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["create", "get", "list", "watch", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: overseer-deployment-rolebinding
  namespace: a8s
subjects:
  - kind: ServiceAccount
    name: default
    namespace: a8s
roleRef:
  kind: Role
  name: overseer-deployment-role
  apiGroup: rbac.authorization.k8s.io 